- openid-federation-1_0.xml
preview here:
https://openid.github.io/federation/intr-app-prot-neutr.html
> introduction improved, oidfed can be used with any other protocols

- openid-federation-1_0.xml
This PR closes https://github.com/openid/federation/issues/18
> Clarifications about trust marks in the resolve endpoint response

- openid-federation-1_0.xml
This PR closes https://github.com/openid/federation/issues/19
> Clarifications about the publication of the Federation Entity Keys

- openid-federation-1_0.xml
> Entity Identifiers use the https scheme

- openid-federation-1_0.xml
In response to Alexey Melnikov's feedback in "[media-types] Re: [IANA #1369075] application/entity-statement+jwt registration request" as designated expert
> Add section defining each media type

- openid-federation-1_0.xml
> Simplify obtaining Entity Configurations

- openid-federation-1_0.xml
Fixes #30 
Replaces #31
Cc: @jcmelati
> Simplify fetch endpoint to only return Subordinate Statements

- openid-federation-1_0.xml
This PR Closes https://github.com/openid/federation/issues/42
> fix: Figure 4 and 5 labels

- openid-federation-1_0.xml
> Providing "iss" should not be required at the fetch endpoint

- openid-federation-1_0.xml
this PR closes https://github.com/openid/federation/issues/66
> fix: trust chain evaluation delegation with resolve

- openid-federation-1_0.xml
> Rename Resolve Entity Statement to Resolve Entity

- openid-federation-1_0.xml
> Tighten Trust Chain signature validation wording

- openid-federation-1_0.xml
Per feedback from the IANA Designated Expert.
> Improve descriptions of JWT claims being registered

- openid-federation-1_0.xml
> Allow multiple type request parameters in resolve requests

- openid-federation-1_0.xml
> Add request_authentication_signing_alg_values_supported to example

- openid-federation-1_0.xml
> State that Compact Serializations are used

- openid-federation-1_0.xml
> Require validating explicit typing of JWTs

- openid-federation-1_0.xml
> authority_hints contains Entity Identifiers of Immediate Superiors

- openid-federation-1_0.xml
> Explicitly type signed JWK Sets

- openid-federation-1_0.xml
> Clarified that PAR requests use Request Objects

- openid-federation-1_0.xml
> Describe validation of resolved metadata

- openid-federation-1_0.xml
> Audience for Endpoint Client Authentication is Entity Identifier

- openid-federation-1_0.xml
This PR fixes https://github.com/openid/federation/issues/101
> fix: issuer must match the federation entity id

- openid-federation-1_0.xml
> Restrict aud values to Entity Identifier of recipient

- openid-federation-1_0.xml
> Require kid in Signed JWK Set JWTs

- openid-federation-1_0.xml
> Describe why and how to not support request_uri

- openid-federation-1_0.xml
> Clarify Trust Mark validation

- openid-federation-1_0.xml
> Informatively say that two OP metadata parameters can be used

- openid-federation-1_0.xml
> Federation Entity Keys MUST NOT appear in metadata

- openid-federation-1_0.xml
> Clarify description of using request objects

- openid-federation-1_0.xml
This PR resolves https://github.com/openid/federation/issues/132
however, I have to report @selfissued, the term Final Metadata is often used within the draft.
Do we have to change it to Resolved Metadata for consistency?
> fix: lables in figure

- openid-federation-1_0.xml
> token_endpoint_auth_method with Automatic Registration

- openid-federation-1_0.xml
Fixes #7 
Fixes #86 
Fixes #134 
Fixes #148 
As @Razumain wrote in https://github.com/openid/federation/issues/148#issuecomment-2500857465 :
> The role of this specification is not to prevent bad federation setups, nor it is the role of this specification to fix it in the available protocols. Doing so will impose unrealistic complexity on chain validation algorithms.
Provide implementers and deployers guidance to that effect.
> Provide implementation considerations on Federation topologies

- openid-federation-1_0.xml
> Use consistent parameter and claim names

- openid-federation-1_0.xml
> Fix lowercase letter typo at beginning of sentence

- openid-federation-1_0.xml
> Clarify Trust Chain selection during Explicit Registration

- openid-federation-1_0.xml
> Described using and not using a provided Trust Chain during Automatic Registration

- openid-federation-1_0.xml
this PR resolves https://github.com/openid/federation/issues/162
> trust mark typ value and id moved to trust_mark_id

- openid-federation-1_0.xml
> Prohibit loops in Trust Chains

- openid-federation-1_0.xml
See [issue 170](https://github.com/openid/federation/issues/170)
> Clarified Trust Mark logo claim definition

- openid-federation-1_0.xml
> Request Objects can be passed by value or by reference

- openid-federation-1_0.xml
Whether they are general or not.
If some part of the document says it can be in an Entity Statement then it should be listed in the Entity Statement section.
> All claims we list as possible in an Entity Statement should be listed in section 3

- openid-federation-1_0.xml
Resolves https://github.com/openid/federation/issues/172
> Added Resolved Metadata in the defined terms

- openid-federation-1_0.xml
Resolves https://github.com/openid/federation/issues/185
> even if topologies may contains loops, trust chain not

- openid-federation-1_0.xml
> Add note about metadata policy and comparing JSON objects

- openid-federation-1_0.xml
> Use Resolved Metadata term in Explicit Registration

- openid-federation-1_0.xml
> Add String Operations section

- openid-federation-1_0.xml
> Clarified that "metadata" declares the roles that an Entity plays

- openid-federation-1_0.xml
> Recommend way to validate non-expiring Trust Marks

- openid-federation-1_0.xml
Add IANA registrations corresponding to metadata parameters added in #224.
Also added protected resource metadata registrations, now that that registry exists.
> Add IANA registrations for new metadata and resource metadata values

- openid-federation-1_0.xml
> Application of constraints on Trust Chain resolution

- openid-federation-1_0.xml
Pull request to resolve https://github.com/openid/federation/issues/247
> Trust Mark Claim Clarification
