openid-federation-1_0.xml

Added a clarification suggested by @jricher in his role as Designated Expert for the IANA OAuth Dynamic Client Registration Metadata registry.

Additional client_registration_types MAY be defined and used

---

openid-federation-1_0.xml

As suggested by @hannestschofenig during his review in his role of Designated Expert for the IANA "OAuth Extensions Error Registry" registry.

Corrected Usage Location for IANA error registrations

---

openid-federation-1_0.xml

In some of the examples the values where strings instead of arrays.

Operator value for 'add' MUST be an array.

---

openid-federation-1_0.xml

We where missing an example of what a Trust Mark looks like if issued by a trust mark issuer that works on delegation from a trust mark ID owner.

An example of Trust Mark delegation.

---

openid-federation-1_0.xml

Fixes #46 
Cc: @SECtim @malmgren01DF

Preventing use of Request Object for private_key_jwt client authentication

---

openid-federation-1_0.xml

To move the discussion on #24 forward I submit a proposal to remove the `iat` and `trust_mark` parameters from the trust mark status endpoint.

remove iat and trust_mark parameters from trust mark status endpoint; #24

---

openid-federation-1_0.xml

Fixes #34 
Replaces `request_authentication_methods_supported` with `pushed_authentication_methods_supported`.  This simplifies things by eliminating the `request_object` request authentication method, since signed requests are always required.  The PR also removes `tls_client_auth` from the supported request authentication methods.
Fixes #98 
Requires the audience when using `private_key_jwt` to be the Authorization Server's Entity Identifier.

Simplified use of PAR for request authentication

---

openid-federation-1_0.xml

As noted in my issue #11 I think the current phrasing on merging the `essential` policy operator is not clear enough.
This is my proposal on how to simplify the phrasing, as I think the semantic should be.

clarify merging of essential policy operators

---

openid-federation-1_0.xml

Define successful and error responses for Automatic Registration

---

openid-federation-1_0.xml

The [Processing of the Request by the OP](https://openid.net/specs/openid-federation-1_0-ID4.html#name-processing-of-the-request-b) section described both request processing and response creation before this PR.  This PR divides them into separate request processing and response creation sections, without making normative changes to the text.

Have Explicit Registration sections start and stop in right places

---

openid-federation-1_0.xml

to prevent confusion between Explicit Registration responses and normal Entity Statements.

Define application/explicit-registration-response+jwt media type

---

openid-federation-1_0.xml

Sometimes we say "Seconds Since the Epoch, as defined in".
Sometimes we say "Seconds Since the Epoch, per".
This PR uses the second, more concise form, in all cases.

Make Seconds Since the Epoch language consistent

---

openid-federation-1_0.xml

Fixes https://github.com/openid/federation/issues/143
Trust Mark issuers and Trust Mark owners are first class citizens in the OID federation ecosystem and hence should be introduced in the terminology.
This change
- Moves definition of Trust Mark issuer from chapter 7 to terminology
- Moves definition of Trust Mark owner from chapter 7 to terminology
- Removes definition for Trust Mark issuer and Trust Mark owner from chapter 7
- Updates all occurances of Trust Mark issuer to Trust Mark Issuer
- Updates all occurances of Trust Mark owner to Trust Mark Owner
- Adds clarification on Trust Mark identifier to Trust Mark terminiology as Trust Mark identifier is lateron used in Trust Mark Owner definition

Move Trust Mark issuers and Trust Mark owners into the terminology

---

openid-federation-1_0.xml

Fixes #136
Note that we probably also want to harmonize `missing_trust_anchor` with `invalid_trust_anchor` and `trust_chain_validation_failed` with `invalid_trust_chain`.

Define additional error codes

---

openid-federation-1_0.xml

Several are missing the required explicit type values, such as `"typ":"trust-mark+jwt"`.

Correct base64url-encoded examples

---

openid-federation-1_0.xml

To address the root issue of #35  - how to deal with JSON object values in metadata policies and metadata.
This was adopted from the JSON Path RFC, which language must exhibit predictable behaviour, but this isn't guaranteed when the JSON is non-interoperable (e.g. has duplicate JSON object member names):
https://www.rfc-editor.org/rfc/rfc9535#name-json-values
> The parsing of a JSON text into a JSON value and what happens if a JSON text does not represent valid JSON are not defined by this document. Sections [4](https://rfc-editor.org/rfc/rfc8259#section-4) and [8](https://rfc-editor.org/rfc/rfc8259#section-8) of [[RFC8259](https://www.rfc-editor.org/rfc/rfc9535#RFC8259)] identify specific situations that may conform to the grammar for JSON texts but are not interoperable uses of JSON, …

Using non-interoperable JSON may result in unpredictable metadata and metadata policies (iss #35)

---

openid-federation-1_0.xml

Allow multiple Trust Anchor values in resolve requests

---

openid-federation-1_0.xml

Addresses issue  #178.
* Updates the introduction to the "OpenID Connect Client Registration" section.
* Aligns the style of the `client_registration_types_supported` with `client_registration_types`.
* Tightens intro paragraph re OIDC and OAuth.

Clarify that other client registration methods can be used with OpenID Federation 1.0

---

openid-federation-1_0.xml

Addresses issues #11 , #129 , #180.
The chief aim of this PR is to make it easier for architects to devise metadata policies in federations with multiple Trust Anchors or federations with complex topologies. In a single-anchored federation the current, limited operator combinations were okay, because one can simply lookup the policies of the Superior(s) and tweak the local policy where necessary. When dealing with multiple Trust Anchors the limited combinations become a problem. This PR fixes that. It also fixes the `value` + `essential` combination, which current spec may lead to policy conflict (#180).
This PR incorporates the contributions of @zachmann from PRs #111 and #112 (thanks!), with slight edits , plus several additional combination changes.
The proposed combinations were …

Adjust and simplify policy operator combinations

---

openid-federation-1_0.xml

As per the RFC 5280, `naming constraints` applied to URIs `MUST be specified as a fully qualified domain name and MAY specify a host or a domain. Examples would be "host.example.com" and ".example.com"`.
The current specification incorrectly shows examples with URI scheme prefixes, such as "https://.example.com", which do not conform to RFC 5280.

fix: naming constraints example

---

openid-federation-1_0.xml

Apart from the fact that the set of entity type in the request response MUST be the same as in the request the metadata for each type in the response must be validated against the metadata policies in a trust chain collected based on the response claims **trust_anchor_id** and **authority_hints**.

An explicit client registration may contain metadata for more than one entity_type.

---

openid-federation-1_0.xml

The outputs of rows and 3 and 4 must be empty JSON array [].
This aligns the examples with the spec update for iss #182 .

Fixes the policy operators examples table: output of rows 3 and 4 must be empty JSON array (iss #196)

---

openid-federation-1_0.xml

Clarify requirement for exp time in Trust Anchor Entity Configuration

---

openid-federation-1_0.xml

Added note about using different signing algorithms for different Entity Statements in a Trust Chain.
@selfissued I would appreciate to add normaitve reference to standards defining the supported algorithm and the security best current practice to exclude the deprecated/weak ones.

different signing algorithms for different Entity Statements in a Trust Chains

---

openid-federation-1_0.xml

As we are currently working on a draft for an [Entity Collection Endpoint](https://github.com/zachmann/openid-federation-entity-collection) we found the need for additional metadata claims.
This allows that Entities publish this information in their Entity Configuration and the entity collection endpoint can return the information which then among other use-cases allows to build UIs so End-Users can select an OP.
This PR adds the following claims as **optional** metadata claims that can be used with all entity types:
- display_name
- description
- keywords
- information_uri
This is also inspired by https://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-metadata-ui/v1.0/os/sstc-saml-metadata-ui-v1.0-os.html
I tried to mimic the information specified there, where `policy_uri` and …

Add additional ui related claims for all metadata types.

---

openid-federation-1_0.xml

Describe Client Authentication with Automatic Registration

---

openid-federation-1_0.xml

#238 was merged. I commented on that PR: https://github.com/openid/federation/pull/238#discussion_r2275430436
This PR clarifies that for trust marks not recognized within a federation the validation step 1 is optional.
This is very logical, since this step is not possible for trust marks not recognized within a federation. However, for me it felt like a contraction to mandate the validation to be done, even thought allowing that trust marks not listed there still might be used.
Therefore, I added this statement to clarify this.

clarify validation of trust marks not recognized within the federation
